fix

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -15,17 +15,19 @@ jobs:
     container: ghcr.io/epitech/coding-style-checker:latest
     steps:
     - uses: actions/checkout@v4
+      if: ${{ !contains(env.MIRROR_URL, github.repository) }}
     - name: Check coding style
+      if: ${{ !contains(env.MIRROR_URL, github.repository) }}
       run: |
-          check.sh $(pwd) $(pwd)
-          while IFS=: read -r file line type msg; do
-            echo "::error file=${file#./},line=$line,title=$type::$msg"
-          done < $(pwd)/coding-style-reports.log
-          if [ -s $(pwd)/coding-style-reports.log ]; then
-            exit 1
-          else
-            echo "No coding style errors detected"
-          fi
+        check.sh $(pwd) $(pwd)
+        while IFS=: read -r file line type msg; do
+          echo "::error file=${file#./},line=$line,title=$type::$msg"
+        done < $(pwd)/coding-style-reports.log
+        if [ -s $(pwd)/coding-style-reports.log ]; then
+          exit 1
+        else
+          echo "No coding style errors detected"
+
   check_program_compilation:
     needs: check_coding_style
     runs-on: ubuntu-latest
@@ -33,11 +35,14 @@ jobs:
     container: epitechcontent/epitest-docker
     steps:
     - uses: actions/checkout@v4
+      if: ${{ !contains(env.MIRROR_URL, github.repository) }}
     - name: Compile program
+      if: ${{ !contains(env.MIRROR_URL, github.repository) }}
       run: |
         make
         make clean
     - name: Check executables
+      if: ${{ !contains(env.MIRROR_URL, github.repository) }}
       run: |
         for file in ${{ env.EXECUTABLES }}; do
           if [ ! -x "${{ env.EXECUTABLES }}" ]; then
@@ -45,29 +50,31 @@ jobs:
             exit 1
           fi
         done
+
   run_tests:
     needs: check_program_compilation
     runs-on: ubuntu-latest
     container: epitechcontent/epitest-docker
     steps:
     - uses: actions/checkout@v4
+      if: ${{ !contains(env.MIRROR_URL, github.repository) }}
     - name: Run tests
+      if: ${{ !contains(env.MIRROR_URL, github.repository) }}
       run: |
         make tests_run
+
   push_to_mirror:
-      runs-on: ubuntu-latest
-      needs: [check_program_compilation, check_coding_style, run_tests]
-      steps:
-          - name: Checkout
-            uses: actions/checkout@v4
-            if: ${{ !contains(env.MIRROR_URL, github.repository) }}
-            with:
-              fetch-depth: 0
-          - name: Push Epitech
-            if: ${{ !contains(env.MIRROR_URL, github.repository) }}
-            uses: pixta-dev/repository-mirroring-action@v1
-            with:
-              target_repo_url:
-                ${{ env.MIRROR_URL }}
-              ssh_private_key:
-                ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+    runs-on: ubuntu-latest
+    needs: [check_program_compilation, check_coding_style, run_tests]
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v4
+      if: ${{ !contains(env.MIRROR_URL, github.repository) }}
+      with:
+        fetch-depth: 0
+    - name: Push Epitech
+      if: ${{ !contains(env.MIRROR_URL, github.repository) }}
+      uses: pixta-dev/repository-mirroring-action@v1
+      with:
+        target_repo_url: ${{ env.MIRROR_URL }}
+        ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
